import type { NextPage } from 'next';
import Head from 'next/head';
import { Track } from '@uniformdev/context-react';
import { Page } from '../graphql-types';
import Navbar from './Navbar';
import Footer from './Footer';
import { PageComponentsList } from './PageComponentsList';
import { EnrichmentData } from '@uniformdev/context';

export type PageProps = {
  preview: boolean;
  page: Page;
};

const Page: NextPage<PageProps> = ({ page }) => {
  const behaviour: EnrichmentData[] = [];
  // //@todo fork "contentful-typescript-codegen" package to support Context fields formats
  if (page.uniformContextEnrichmentTagging) {
    behaviour.push(...page.uniformContextEnrichmentTagging);
  }
  return (
    <Track behavior={behaviour}>
      <Navbar />
      <Head>
        <title>Uniform Context + Contentful + NextJS</title>
        <meta name="description" content="Generated by create next app, modified with typescript, etc" />
      </Head>
      {page.components && <PageComponentsList components={page.components} />}
      <Footer />
    </Track>
  );
};

export default Page;
